[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
index = sysmon
renderXml = true

[WinEventLog://OpenSSH/Operational]
disabled = 0
index = main
renderXml = true

[WinEventLog://Security]
disabled = 0
index = main
renderXml = true

[WinEventLog://Microsoft-Windows-Security-Auditing/Authentication]
disabled = 0
index = main
renderXml = true
